<?php

/**
 * OpenCart / PIT connection config (v0.5.7, v1.7.1 live sync test, v1.8.2 Sync/API Settings, v2.4.9 supplier queue).
 * Credentials stay on server — do not commit live API keys to Git.
 * Server overrides: config/opencart.local.php (gitignored) or copy from config/opencart.local.example.php
 * Staging template: config/opencart.staging.example.php
 */
return [
    'source_mode' => 'demo',
    'enabled' => false,
    'demo_mode' => true,
    'api_base_url' => '',
    'api_key' => '',
    'business_source_id' => 1,
    'default_supplier_id' => 1,
    'read_only_lock' => true,
    'product_sync_enabled' => true,
    'order_sync_enabled' => true,
    'dispatch_bridge_required' => true,
    'max_rows_per_page' => 20,
    'max_orders_per_request' => 20,
    'max_products_per_request' => 20,
    'order_sync_mode' => 'connector_queue',
    'order_api_route' => 'api/ibs/orders',
    'order_queue_api_route' => 'api/ibs/order_queue_statuses',
    'connection_test_api_route' => 'api/ibs/connection_test',
    'product_api_route' => 'demo/warehouse_product',
    'api_page_param' => 'page',
    'api_limit_param' => 'limit',
    'dispatch_location_bridge_table' => 'dispatch_location_product',
    'skip_status_ids' => ['0'],
    'skip_status_names' => ['Missing', 'missing'],
    'supplier_handled_workflow_groups' => ['workflow', 'supplier_handled'],
    'courier_only_workflow_groups' => ['courier', 'courier_reference'],
    'courier_stage_ibs_statuses' => ['in_review', 'in_transit', 'out_for_delivery', 'delivered', 'order_returning'],
    'order_sync_advanced_mapping' => false,
    'order_sync_min_source_order_id' => 0,
    'hide_demo_orders_in_workflow' => true,
    'block_demo_orders_from_dispatch' => true,
    'skip_demo_orders_in_sync' => true,
    'demo_source_order_reference_prefixes' => ['OC-1000'],
    'allowed_initial_ibs_statuses' => [
        'new_order',
        'order_received',
        'packaging',
        'shipped',
        'hold',
        'cancelled',
    ],
    'extension_table_probe' => [
        'poip_product_option_value',
        'product_option_value_image',
        'improved_option_value',
        'relatedoptions',
        'related_options',
    ],
    'option_image_db_enrichment' => true,
    'db_readonly_allowed' => false,
    'db' => [
        'host' => '',
        'database' => '',
        'username' => '',
        'password' => '',
        'prefix' => 'oc_',
    ],
    'demo_queue_statuses' => [
        ['status_id' => '3', 'name' => 'Supplier Processing', 'selected' => true],
        ['status_id' => '5', 'name' => 'Out For Delivery', 'selected' => true],
        ['status_id' => '7', 'name' => 'Returning', 'selected' => true],
        ['status_id' => '99', 'name' => 'Unmapped Custom Status', 'selected' => false],
    ],
    'demo_warehouse_products' => [
        [
            'product_id' => '501',
            'name' => 'Demo Warehouse Stroller',
            'model' => 'OC-STROLLER-501',
            'quantity' => 12,
            'price' => 4500.00,
            'status' => 1,
            'image' => '',
            'from_warehouse' => 1,
        ],
        [
            'product_id' => '502',
            'name' => 'Demo Shop-Only Item',
            'model' => 'OC-SHOP-502',
            'quantity' => 99,
            'price' => 1200.00,
            'status' => 1,
            'from_warehouse' => 0,
        ],
        [
            'product_id' => '503',
            'name' => 'Demo Variable Stroller',
            'model' => 'OC-VAR-503',
            'quantity' => 20,
            'price' => 5200.00,
            'status' => 1,
            'from_warehouse' => 1,
            'type' => 'variable',
            'options' => [
                [
                    'option_id' => '11',
                    'option_value_id' => '101',
                    'option_name' => 'Color',
                    'option_value' => 'Blue',
                    'model' => 'OC-VAR-503-BLU',
                    'quantity' => 8,
                    'price' => 200.00,
                    'price_prefix' => '+',
                    'subtract' => 1,
                    'required' => 1,
                    'image' => 'catalog/demo/stroller-blue.png',
                ],
                [
                    'option_id' => '11',
                    'option_value_id' => '102',
                    'option_name' => 'Color',
                    'option_value' => 'Red',
                    'model' => 'OC-VAR-503-RED',
                    'quantity' => 12,
                    'price' => 150.00,
                    'price_prefix' => '+',
                    'subtract' => 1,
                    'required' => 1,
                    'image' => 'catalog/demo/stroller-red.png',
                ],
            ],
        ],
        [
            'product_id' => '504',
            'name' => 'Demo Variable No Options',
            'model' => 'OC-VAR-504',
            'quantity' => 5,
            'price' => 3800.00,
            'status' => 1,
            'from_warehouse' => 1,
            'type' => 'variable',
            'options' => [],
        ],
        [
            'product_id' => '505',
            'name' => 'Demo Warehouse Carrier',
            'model' => 'OC-CARRIER-505',
            'quantity' => 7,
            'price' => 2900.00,
            'status' => 1,
            'from_warehouse' => 1,
        ],
    ],
    'demo_orders' => [
        [
            'order_id' => '10001',
            'source_order_id' => '10001',
            'source_order_reference' => 'OC-10001',
            'source_invoice_reference' => 'INV-10001',
            'order_status_id' => '3',
            'source_status_id' => '3',
            'order_status' => 'Supplier Processing',
            'source_status' => 'Supplier Processing',
            'connector_queue_status' => '3',
            'connector_queue_label' => 'Supplier Processing',
            'in_supplier_queue' => true,
            'customer_name' => 'Demo Customer A',
            'customer_phone' => '01700000001',
            'customer_address' => 'Dhaka, Bangladesh',
            'order_total' => 1500.00,
            'courier_status' => 'Pending Pickup',
            'consignment_id' => 'CON-10001',
            'courier_name' => 'Steadfast',
            'products' => [
                [
                    'product_id' => '501',
                    'name' => 'Demo Warehouse Stroller',
                    'variant_label' => null,
                    'quantity' => 1,
                    'price' => 1500.00,
                    'sku' => 'OC-STROLLER-501',
                    'from_warehouse' => 1,
                ],
            ],
        ],
        [
            'order_id' => '10002',
            'source_order_id' => '10002',
            'source_order_reference' => 'OC-10002',
            'source_invoice_reference' => 'INV-10002',
            'order_status_id' => '7',
            'source_status_id' => '7',
            'order_status' => 'Returning',
            'source_status' => 'Returning',
            'connector_queue_status' => '7',
            'connector_queue_label' => 'Returning',
            'in_supplier_queue' => true,
            'customer_name' => 'Demo Customer B',
            'customer_phone' => '01700000002',
            'customer_address' => 'Chittagong, Bangladesh',
            'order_total' => 2200.00,
            'courier_status' => 'Return in transit',
            'consignment_id' => 'CON-10002',
            'products' => [
                [
                    'product_id' => '503',
                    'name' => 'Demo Return Candidate',
                    'variant_label' => 'Color: Blue',
                    'quantity' => 2,
                    'price' => 1100.00,
                    'sku' => 'OC-VAR-503-BLU',
                    'from_warehouse' => 1,
                ],
            ],
        ],
        [
            'order_id' => '10003',
            'source_order_id' => '10003',
            'source_order_reference' => 'OC-10003',
            'source_invoice_reference' => null,
            'order_status_id' => '0',
            'source_status_id' => '0',
            'order_status' => 'Missing',
            'source_status' => 'Missing',
            'connector_queue_status' => '0',
            'connector_queue_label' => 'Missing',
            'in_supplier_queue' => false,
            'customer_name' => 'Skipped Missing',
            'customer_phone' => '',
            'customer_address' => '',
            'order_total' => 0.00,
            'products' => [],
        ],
        [
            'order_id' => '10004',
            'source_order_id' => '10004',
            'source_order_reference' => 'OC-10004',
            'source_invoice_reference' => 'INV-10004',
            'order_status_id' => '99',
            'source_status_id' => '99',
            'order_status' => 'Unmapped Custom Status',
            'source_status' => 'Unmapped Custom Status',
            'connector_queue_status' => '99',
            'connector_queue_label' => 'Unmapped Custom Status',
            'in_supplier_queue' => true,
            'customer_name' => 'Blocked Unmapped',
            'customer_phone' => '01700000004',
            'customer_address' => 'Sylhet',
            'order_total' => 500.00,
            'products' => [
                [
                    'product_id' => '501',
                    'name' => 'Demo Warehouse Stroller',
                    'quantity' => 1,
                    'price' => 500.00,
                    'sku' => 'OC-STROLLER-501',
                    'from_warehouse' => 1,
                ],
            ],
        ],
        [
            'order_id' => '10005',
            'source_order_id' => '10005',
            'source_order_reference' => 'OC-10005',
            'source_invoice_reference' => 'INV-10005',
            'order_status_id' => '5',
            'source_status_id' => '5',
            'order_status' => 'Out For Delivery',
            'source_status' => 'Out For Delivery',
            'connector_queue_status' => '5',
            'connector_queue_label' => 'Out For Delivery',
            'in_supplier_queue' => true,
            'customer_name' => 'Courier Only Demo',
            'customer_phone' => '01700000005',
            'customer_address' => 'Rajshahi',
            'order_total' => 800.00,
            'courier_status' => 'Out for delivery',
            'consignment_id' => 'CON-10005',
            'products' => [
                [
                    'product_id' => '501',
                    'name' => 'Demo Warehouse Stroller',
                    'quantity' => 1,
                    'price' => 800.00,
                    'sku' => 'OC-STROLLER-501',
                    'from_warehouse' => 1,
                ],
                [
                    'product_id' => '502',
                    'name' => 'Demo Shop-Only Item',
                    'quantity' => 1,
                    'price' => 0.00,
                    'sku' => 'OC-SHOP-502',
                    'from_warehouse' => 0,
                ],
            ],
        ],
    ],
];
