<?php

/**
 * OpenCart / PIT connection config (v0.5.7, v1.7.1 live sync test).
 * Credentials stay on server — do not commit live API keys to Git.
 * Staging template: config/opencart.staging.example.php (api_base_url = staging.lokkisona.com).
 */
return [
    'enabled' => false,
    'demo_mode' => true,
    'api_base_url' => '',
    'api_key' => '',
    'business_source_id' => 1,
    'default_supplier_id' => 1,
    'max_rows_per_page' => 20,
    'max_orders_per_request' => 20,
    'max_products_per_request' => 20,
    'order_api_route' => 'api/order',
    'product_api_route' => 'demo/warehouse_product',
    'api_page_param' => 'page',
    'api_limit_param' => 'limit',
    'dispatch_location_bridge_table' => 'dispatch_location_product',
    'skip_status_ids' => ['0'],
    'skip_status_names' => ['Missing', 'missing'],
    'supplier_handled_workflow_groups' => ['workflow', 'supplier_handled'],
    'courier_only_workflow_groups' => ['courier', 'courier_reference'],
    'courier_stage_ibs_statuses' => ['out_for_delivery', 'delivered'],
    'extension_table_probe' => [
        'poip_product_option_value',
        'product_option_value_image',
        'improved_option_value',
        'relatedoptions',
        'related_options',
    ],
    'db_readonly_allowed' => false,
    'db' => [
        'host' => '',
        'database' => '',
        'username' => '',
        'password' => '',
        'prefix' => 'oc_',
    ],
    'demo_warehouse_products' => [
        [
            'product_id' => '501',
            'name' => 'Demo Warehouse Stroller',
            'model' => 'OC-STROLLER-501',
            'quantity' => 12,
            'price' => 4500.00,
            'status' => 1,
            'image' => '',
            'from_warehouse' => 1,
        ],
        [
            'product_id' => '502',
            'name' => 'Demo Shop-Only Item',
            'model' => 'OC-SHOP-502',
            'quantity' => 99,
            'price' => 1200.00,
            'status' => 1,
            'from_warehouse' => 0,
        ],
        [
            'product_id' => '503',
            'name' => 'Demo Variable Stroller',
            'model' => 'OC-VAR-503',
            'quantity' => 20,
            'price' => 5200.00,
            'status' => 1,
            'from_warehouse' => 1,
            'type' => 'variable',
            'options' => [
                [
                    'option_id' => '11',
                    'option_value_id' => '101',
                    'option_name' => 'Color',
                    'option_value' => 'Blue',
                    'model' => 'OC-VAR-503-BLU',
                    'quantity' => 8,
                    'price' => 200.00,
                    'price_prefix' => '+',
                    'subtract' => 1,
                    'required' => 1,
                    'image' => '',
                ],
                [
                    'option_id' => '11',
                    'option_value_id' => '102',
                    'option_name' => 'Color',
                    'option_value' => 'Red',
                    'model' => 'OC-VAR-503-RED',
                    'quantity' => 12,
                    'price' => 150.00,
                    'price_prefix' => '+',
                    'subtract' => 1,
                    'required' => 1,
                ],
            ],
        ],
        [
            'product_id' => '504',
            'name' => 'Demo Variable No Options',
            'model' => 'OC-VAR-504',
            'quantity' => 5,
            'price' => 3800.00,
            'status' => 1,
            'from_warehouse' => 1,
            'type' => 'variable',
            'options' => [],
        ],
        [
            'product_id' => '505',
            'name' => 'Demo Warehouse Carrier',
            'model' => 'OC-CARRIER-505',
            'quantity' => 7,
            'price' => 2900.00,
            'status' => 1,
            'from_warehouse' => 1,
        ],
    ],
    'demo_orders' => [
        [
            'source_order_id' => '10001',
            'source_order_reference' => 'OC-10001',
            'source_invoice_reference' => 'INV-10001',
            'source_status_id' => '3',
            'source_status' => 'Supplier Processing',
            'customer_name' => 'Demo Customer A',
            'customer_phone' => '01700000001',
            'customer_address' => 'Dhaka, Bangladesh',
            'order_total' => 1500.00,
            'courier_status' => 'Pending Pickup',
            'consignment_id' => 'CON-10001',
            'courier_name' => 'Steadfast',
            'items' => [
                [
                    'product_id' => '501',
                    'product_name' => 'Demo Warehouse Stroller',
                    'variant_label' => null,
                    'quantity' => 1,
                    'selling_price' => 1500.00,
                    'sku' => 'OC-STROLLER-501',
                ],
            ],
        ],
        [
            'source_order_id' => '10002',
            'source_order_reference' => 'OC-10002',
            'source_invoice_reference' => 'INV-10002',
            'source_status_id' => '7',
            'source_status' => 'Returning',
            'customer_name' => 'Demo Customer B',
            'customer_phone' => '01700000002',
            'customer_address' => 'Chittagong, Bangladesh',
            'order_total' => 2200.00,
            'courier_status' => 'Return in transit',
            'consignment_id' => 'CON-10002',
            'items' => [
                [
                    'product_id' => '503',
                    'product_name' => 'Demo Return Candidate',
                    'variant_label' => 'Color: Blue',
                    'quantity' => 2,
                    'selling_price' => 1100.00,
                    'sku' => 'OC-VAR-503-BLU',
                ],
            ],
        ],
        [
            'source_order_id' => '10003',
            'source_order_reference' => 'OC-10003',
            'source_invoice_reference' => null,
            'source_status_id' => '0',
            'source_status' => 'Missing',
            'customer_name' => 'Skipped Missing',
            'customer_phone' => '',
            'customer_address' => '',
            'order_total' => 0.00,
            'items' => [],
        ],
        [
            'source_order_id' => '10004',
            'source_order_reference' => 'OC-10004',
            'source_invoice_reference' => 'INV-10004',
            'source_status_id' => '99',
            'source_status' => 'Unmapped Custom Status',
            'customer_name' => 'Blocked Unmapped',
            'customer_phone' => '01700000004',
            'customer_address' => 'Sylhet',
            'order_total' => 500.00,
            'items' => [
                [
                    'product_id' => null,
                    'product_name' => 'Unmapped Status Item',
                    'variant_label' => null,
                    'quantity' => 1,
                    'selling_price' => 500.00,
                    'sku' => 'DEMO-004',
                ],
            ],
        ],
        [
            'source_order_id' => '10005',
            'source_order_reference' => 'OC-10005',
            'source_invoice_reference' => 'INV-10005',
            'source_status_id' => '5',
            'source_status' => 'Out For Delivery',
            'customer_name' => 'Courier Only Demo',
            'customer_phone' => '01700000005',
            'customer_address' => 'Rajshahi',
            'order_total' => 800.00,
            'courier_status' => 'Out for delivery',
            'consignment_id' => 'CON-10005',
            'items' => [
                [
                    'product_id' => '501',
                    'product_name' => 'Demo Warehouse Stroller',
                    'quantity' => 1,
                    'selling_price' => 800.00,
                    'sku' => 'OC-STROLLER-501',
                ],
            ],
        ],
    ],
];
