<?php

return [
    'default_role' => 'owner',
    'roles' => [
        'owner' => [
            'label' => 'Owner',
            'description' => 'Full business owner access across the standalone ERP foundation.',
        ],
        'admin' => [
            'label' => 'Admin',
            'description' => 'Operational administrator access for system and workflow management.',
        ],
        'staff' => [
            'label' => 'Staff',
            'description' => 'Day-to-day operational access with limited management permissions.',
        ],
        'supplier' => [
            'label' => 'Supplier',
            'description' => 'Full supplier business app — fulfillment, products, payables, reports, and tools (scoped to one supplier).',
        ],
    ],
    'groups' => [
        'Core System' => [
            'dashboard.view',
            'health.view',
            'version.view',
            'activity_log.view',
            'roles_permissions.view',
            'database_safety.view',
            'dev_db_activation.view',
            'migrations.view',
            'migrations.manage',
            'migration_runner.view',
            'migration_runner.manage',
            'migration_files.view',
            'migration_files.manage',
            'migration_dry_run.view',
            'migration_dry_run.manage',
            'migration_approval.view',
            'migration_approval.manage',
            'migration_apply.view',
            'migration_apply.manage',
            'migration_execution_lock.view',
            'migration_execution_lock.manage',
            'supplier_opening_balances.view',
            'supplier_opening_balances.manage',
            'supplier_opening_balances.approve',
            'build_queue.view',
            'build_queue.manage',
            'build_automation.view',
            'build_automation.manage',
            'users.view',
            'users.manage',
            'suppliers.view',
            'suppliers.manage',
            'business_sources.view',
            'business_sources.manage',
            'settings.view',
            'settings.manage',
            'sync_api_settings.view',
            'sync_api_settings.manage',
        ],
        'User Management' => [
            'users.view',
            'users.manage',
        ],
        'Migration Runner' => [
            'migrations.view',
            'migrations.manage',
            'migration_runner.view',
            'migration_runner.manage',
            'migration_files.view',
            'migration_files.manage',
            'migration_dry_run.view',
            'migration_dry_run.manage',
            'migration_approval.view',
            'migration_approval.manage',
            'migration_apply.view',
            'migration_apply.manage',
            'migration_execution_lock.view',
            'migration_execution_lock.manage',
        ],
        'Build Queue' => [
            'build_queue.view',
            'build_queue.manage',
            'build_automation.view',
            'build_automation.manage',
        ],
        'Supplier Management' => [
            'suppliers.view',
            'suppliers.manage',
            'supplier_opening_balances.view',
            'supplier_opening_balances.manage',
            'supplier_opening_balances.approve',
        ],
        'Supplier Tools' => [
            'supplier_tools.view',
            'supplier_tools.manage',
            'supplier_quick_invoice.view',
            'supplier_quick_invoice.manage',
            'supplier_calculator.view',
        ],
        'Business Sources' => [
            'business_sources.view',
            'business_sources.manage',
        ],
        'Orders' => [
            'orders.view',
            'orders.manage',
        ],
        'Manual Orders' => [
            'manual_orders.view',
            'manual_orders.manage',
            'external_orders.view',
            'external_orders.manage',
        ],
        'Order Workflow' => [
            'order_workflow.view',
            'order_workflow.manage',
        ],
        'Product Control' => [
            'product_control.view',
            'product_control.manage',
        ],
        'Dispatch' => [
            'dispatch.view',
            'dispatch.manage',
        ],
        'Dispatch Reports' => [
            'dispatch_reports.view',
            'dispatch_reports.manage',
        ],
        'Returns' => [
            'returns.view',
            'returns.manage',
        ],
        'Return Receive' => [
            'return_receive.view',
            'return_receive.manage',
            'return_batches.view',
            'return_batches.manage',
        ],
        'Status Mapping' => [
            'status_mapping.view',
            'status_mapping.manage',
        ],
        'Sync' => [
            'sync.view',
            'sync.manage',
        ],
        'Sync Preview' => [
            'sync_preview.view',
            'sync_preview.manage',
        ],
        'Sync Import' => [
            'sync_import.view',
            'sync_import.manage',
        ],
        'Invoice Printing' => [
            'invoices.view',
            'invoices.manage',
            'invoice_printing.view',
            'invoice_printing.manage',
            'packing_print.view',
            'packing_print.manage',
        ],
        'Payable' => [
            'payable.view',
            'payable.manage',
        ],
        'Supplier Payables' => [
            'payables.view',
            'payables.manage',
            'supplier_payables.view',
            'supplier_payables.manage',
        ],
        'Settlements' => [
            'settlements.view',
            'settlements.manage',
        ],
    ],
    'role_permissions' => [
        'owner' => ['*'],
        'admin' => [
            'dashboard.view',
            'health.view',
            'version.view',
            'activity_log.view',
            'roles_permissions.view',
            'database_safety.view',
            'dev_db_activation.view',
            'migrations.view',
            'migrations.manage',
            'migration_runner.view',
            'migration_runner.manage',
            'migration_files.view',
            'migration_files.manage',
            'migration_dry_run.view',
            'migration_dry_run.manage',
            'migration_approval.view',
            'migration_approval.manage',
            'migration_apply.view',
            'migration_apply.manage',
            'migration_execution_lock.view',
            'migration_execution_lock.manage',
            'supplier_opening_balances.view',
            'supplier_opening_balances.manage',
            'supplier_opening_balances.approve',
            'build_queue.view',
            'build_queue.manage',
            'build_automation.view',
            'build_automation.manage',
            'users.view',
            'users.manage',
            'suppliers.view',
            'suppliers.manage',
            'supplier_tools.view',
            'supplier_tools.manage',
            'supplier_quick_invoice.view',
            'supplier_quick_invoice.manage',
            'supplier_calculator.view',
            'business_sources.view',
            'business_sources.manage',
            'orders.view',
            'orders.manage',
            'manual_orders.view',
            'manual_orders.manage',
            'external_orders.view',
            'external_orders.manage',
            'order_workflow.view',
            'order_workflow.manage',
            'product_control.view',
            'product_control.manage',
            'dispatch.view',
            'dispatch.manage',
            'dispatch_reports.view',
            'dispatch_reports.manage',
            'returns.view',
            'returns.manage',
            'return_receive.view',
            'return_receive.manage',
            'return_batches.view',
            'return_batches.manage',
            'status_mapping.view',
            'status_mapping.manage',
            'sync.view',
            'sync.manage',
            'sync_preview.view',
            'sync_preview.manage',
            'sync_api_settings.view',
            'sync_api_settings.manage',
            'sync_import.view',
            'sync_import.manage',
            'invoices.view',
            'invoices.manage',
            'invoice_printing.view',
            'invoice_printing.manage',
            'packing_print.view',
            'packing_print.manage',
            'payable.view',
            'payable.manage',
            'payables.view',
            'payables.manage',
            'supplier_payables.view',
            'supplier_payables.manage',
            'settlements.view',
            'settlements.manage',
            'settings.view',
            'settings.manage',
        ],
        'staff' => [
            'dashboard.view',
            'orders.view',
            'order_workflow.view',
            'product_control.view',
            'dispatch.view',
            'returns.view',
            'status_mapping.view',
            'sync.view',
            'sync_preview.view',
            'invoices.view',
            'invoice_printing.view',
            'packing_print.view',
        ],
        'supplier' => [
            'dashboard.view',
            'orders.view',
            'order_workflow.view',
            'order_workflow.manage',
            'return_receive.view',
            'return_receive.manage',
            'returns.view',
            'dispatch_reports.view',
            'supplier_payables.view',
            'supplier_payables.manage',
            'settlements.view',
            'product_control.view',
            'product_control.manage',
            'supplier_quick_invoice.manage',
            'supplier_calculator.view',
        ],
    ],
];
