<?php

namespace App\Controllers;

use App\ActivityLog;

class VersionController extends Controller
{
    public function index()
    {
        $this->authorize('version.view');
        ActivityLog::record('version_access', 'Version page viewed');

        $this->render('version.index', [
            'pageTitle' => 'Version',
            'breadcrumbs' => [
                ['label' => 'System', 'active' => false],
                ['label' => 'Version', 'active' => true],
            ],
            'info' => $this->buildVersionInfo(),
        ]);
    }

    private function buildVersionInfo()
    {
        return [
            'product' => config('app.name'),
            'version' => config('app.version'),
            'codename' => config('app.release_label'),
            'release_date' => '2026-06-05',
            'php_version' => PHP_VERSION,
            'php_requirement' => 'PHP 8.2+',
            'environment' => config('app.env'),
            'dependencies' => [
                'OpenCart' => 'None',
                'WooCommerce' => 'None',
                'OCMOD' => 'None',
                'ZIP Installer' => 'None',
            ],
            'features' => [
                'v0.4.2 Dispatch Report Create: POST /dispatch-reports/create builds dispatch batch from ready_for_dispatch orders with dispatch_report_items and cost snapshots',
                'v0.4.1 Order Workflow Action: POST /order-workflow/action with state machine transitions and order_workflow_histories audit rows',
                'v0.4.0 Manual Order Create: POST /manual-orders/create with cost snapshot, duplicate external reference blocking, and bridge to ibs_orders',
                'v0.3.6 Launch Cutover Lock: POST /supplier-opening-balances/launch-lock sets launch_cutovers locked state',
                'v0.3.5 Opening Balance Create/Approve: draft opening balances with owner approval and payable ledger seeding on approve',
                'v0.3.4 Product Cost/Stock Change: cost and stock history tables written on each manual change',
                'v0.3.3 Product/Variant Create/Edit: controlled product and variant forms on /product-control',
                'v0.3.1–v0.3.2 Supplier/Business Source Create/Edit: first write services with CSRF and owner-approved whitelist paths',
                'v0.3.0 Manual Migration Apply Guide: activation checklist and apply order on /migration-files',
                'v0.2.9 Read Foundation QA Gate: full ReadOnlyRepositoryRegistry, model-pending inventory, write-path whitelist for checkpoint',
                'Admin, Activity, and Invoice Read Foundation: /invoice-printing, /activity-log, /users, and /roles-permissions wire InvoiceReadService, ActivityLogReadService, UserReadService, and RoleReadService with read inventory cards for ibs_invoices, ibs_activity_logs, ibs_users, and ibs_roles',
                'Completes read-only coverage for remaining core model contracts: Invoice, ActivityLog (DB contract only), User, and Role',
                'Activity log page keeps file-based App\\ActivityLog runtime logging unchanged while adding separate database read inventory from App\\Models\\ActivityLog',
                'User read inventory redacts sensitive fields such as password_hash in row display via shared read-inventory-card partial',
                'SELECT only on admin pages — no database writes, no user creation, no password change, no role/permission mutation, no invoice creation, no print log creation, no activity log DB write, and no migration apply',
                'Empty-state messages cite migrations 0002_core_users_roles_activity.sql and 0007_invoices_printing_supplier_tools.sql with ibs_ prefixed table names',
                'Dispatch, Return, and Payable Read Foundation: /dispatch-reports, /return-receive, and /supplier-payables wire DispatchReportReadService, ReturnReceiveReadService, and PayableLedgerReadService with read inventory cards for ibs_dispatch_reports, ibs_return_receives, and ibs_payable_ledgers',
                'New SELECT-only repositories and read services for DispatchReport, ReturnReceive, and PayableLedger following the existing BaseReadOnlyRepository pattern',
                'SELECT only on dispatch, return, and payable pages — no database writes, no dispatch batch creation, no return receive submit, no payable ledger creation, no supplier payment, no settlement action, and no migration apply',
                'Empty-state messages cite migration 0006_dispatch_returns_payables.sql and ibs_ prefixed table names when tables are not manually applied yet',
                'Order and Order Item Read Foundation: /order-workflow wires OrderReadService, OrderItemReadService, and OrderWorkflowHistoryReadService with read inventory cards for ibs_orders, ibs_order_items, and ibs_order_workflow_histories',
                'New SELECT-only repositories and read services for Order, OrderItem, and OrderWorkflowHistory following the existing BaseReadOnlyRepository pattern',
                'Order Workflow hybrid page keeps planning foundation content and adds Read-Only Order Workflow Inventory (v0.2.6) with try/catch fallbacks and up to 50 SELECT rows per table',
                'SELECT only on order workflow — no database writes, no order status action, no workflow mutation, no sync/import, and no migration apply from this page',
                'Empty-state messages cite migration 0005_orders_manual_orders_workflow.sql and ibs_ prefixed table names when tables are not manually applied yet',
                'Opening Balance and Launch Cutover Read Foundation: /supplier-opening-balances wires SupplierOpeningBalanceReadService and LaunchCutoverReadService with separate read inventory cards for ibs_supplier_opening_balances and ibs_launch_cutovers',
                'Supplier Opening Balances hybrid page keeps planning foundation content and adds Read-Only Opening Balance / Launch Cutover Inventory (v0.2.5) with try/catch fallbacks and up to 50 SELECT rows per table',
                'SELECT only on supplier opening balances — no database writes, no payable ledger creation, no launch lock action, and no migration apply from this page',
                'Empty-state messages cite migration 0008_supplier_opening_balances_launch_cutovers.sql and ibs_ prefixed table names when tables are not manually applied yet',
                'Product and Variant Read Foundation: /product-control wires ProductReadService and ProductVariantReadService with separate read inventory cards for ibs_products and ibs_product_variants',
                'Product Control hybrid page keeps planning foundation content and adds Read-Only Product Inventory (v0.2.4) with try/catch fallbacks and up to 50 SELECT rows per table',
                'Shared read-inventory-card partial now accepts a configurable card title for reuse across suppliers, business sources, and product control pages',
                'SELECT only on product control — no database writes, no sync, no stock change, no product cost change, and no migration apply from this page',
                'Supplier and Business Source Read Foundation: /suppliers and /business-sources wire SupplierReadService and BusinessSourceReadService with graceful empty states when MySQL or tables are unavailable',
                'Hybrid module pages keep planning foundation content and add a live Read-Only Inventory card showing connection status, table readiness, model contract columns, row count, and up to 50 SELECT rows',
                'Read inventory builders use try/catch around read service construction and never throw fatal errors when the database is down or migration 0003 is not applied yet',
                'Empty-state messages cite prefixed table names (ibs_*) and manual migration 0003_business_sources_suppliers_products.sql with no page-load schema repair',
                'SELECT only on supplier and business source pages — no database writes, no sync, and no migration apply; write services remain a future owner-approved build',
                'Database Service Layer Read-Only Foundation: app/Database helpers (Connection, TableName, QueryGuard, ReadOnlyQueryException) and evolved App\\Database facade for SELECT-only access',
                'Read-only repository layer under app/Repositories with BaseReadOnlyRepository, ReadOnlyRepositoryRegistry, and six repositories for suppliers, business sources, products, product variants, supplier opening balances, and launch cutovers',
                'Read-only service layer under app/Services/ReadOnly with thin delegation and no write methods',
                'QueryGuard enforces SELECT, SHOW, DESCRIBE, and EXPLAIN only and rejects mutation SQL keywords at repository runtime',
                'TableName resolves ibs_ prefixed physical table names from model logical table contracts',
                'Database Safety page shows read-only repository inventory, query guard status, and per-table existence probes with row counts when tables exist',
                'Health check includes Read-Only Query Guard active status',
                'All core module and admin planning pages now show live read-only inventory where model contracts exist, including Invoice Printing, Activity Log DB inventory, Users, and Roles/Permissions',
                'Checkpoint database safety scan extended to block runtime mutation SQL in PHP code',
                'No CRUD screens, no database writes, no migration apply, no OpenCart/WooCommerce connection, and no live planning-page data replacement in this version',
                'Core Model Layer and Database Contract Foundation: app/Models classes are pure metadata contracts (table, ordered columns, explicit primary key) aligned to the manual migration drafts',
                'All 16 existing model column contracts corrected to exactly match draft tables in database/migrations (users, roles, activity_logs, business_sources, suppliers, products, product_variants, orders, order_items, order_workflow_histories, dispatch_reports, return_receives, payable_ledgers, invoices, supplier_opening_balances, launch_cutovers)',
                'New metadata-only App\\Models\\BaseModel with read-only table(), columns(), and primaryKey() accessors and no PDO, query, save, find, create, mutation, or schema logic',
                'New read-only App\\Models\\ModelRegistry providing an in-memory table-to-model map with no filesystem scanning side effects and no database calls',
                'App\\Models\\ActivityLog documented as a future database contract only and kept separate from the current file-based runtime logger App\\ActivityLog',
                'Remaining migration draft tables without a class are recorded as model pending rather than mass-adding new model classes in this version',
                'Model layer performs no SQL execution, no migration apply, and no database writes',
                'Supplier Opening Balance and Launch Cutover planning foundation page and sidebar item',
                'Supplier opening balance permissions for supplier_opening_balances.view, supplier_opening_balances.manage, and supplier_opening_balances.approve',
                'Opening balance planning documents payable-to-supplier, advance-from-supplier, neutral-zero-start, cut-off date, supplier/source selection, reference notes, proof attachment planning, owner approval, audit logging, and adjustment safety',
                'Example opening payable for Iqbal & Brothers documents estimated 1,200,000 BDT as a launch starting balance, not normal order payable',
                'Launch Cutover checklist documents go-live date, cut-off date, old manual payable confirmation, supplier/source confirmation, proof support, owner approval, lock after launch, and separation from new ERP transactions',
                'Supplier Payables, Suppliers, Manual Orders, Dispatch Reports, Return Receive, Build Queue, Dashboard, README, tools, and database docs now describe old manual balance vs new ERP ledger boundaries',
                'Migration Execution Lock planning foundation page and sidebar item',
                'Migration execution lock permissions for migration_execution_lock.view and migration_execution_lock.manage',
                'Execution lock planning documents manual-only apply protection, wrong environment protection, dirty Git protection, failed dry-run protection, missing approval protection, backup missing protection, checksum mismatch protection, double-apply protection, emergency stop planning, and final lock state preview',
                'Planned execution lock and lock audit fields documented without SQL execution, lock record writes, or migration execution code',
                'Migration Runner, Approval, Dry Run, Files, Database Safety, Build Queue, Dashboard, README, and tools docs now describe the draft to dry-run to approval gate to execution lock workflow',
                'Migration Apply Approval Gate planning foundation page and sidebar item',
                'Migration approval and apply permissions for migration_approval.view, migration_approval.manage, migration_apply.view, and migration_apply.manage',
                'Approval gate planning documents dry-run pass, database backup confirmation, environment confirmation, owner/admin approval, Red Issues clear state, checksum confirmation, apply order review, rollback plan review, production warning, and final apply lock planning',
                'Planned migration approval, approval checklist, and approval audit fields documented without SQL execution or approval record writes',
                'Migration Runner, Dry Run, Files, Database Safety, and Build Queue pages now state that future migration apply requires the manual approval gate',
                'Migration Dry Run Validator planning foundation page and sidebar item',
                'Migration dry-run permissions for migration_dry_run.view and migration_dry_run.manage',
                'Dry-run planning documents migration file scanning, SQL safety scanning, apply-order validation, duplicate migration key checks, checksum planning, environment safety, backup reminder, owner approval, and Red Issues Summary behavior',
                'Planned dry-run result and issue fields documented without executing SQL or writing records',
                'Migration Runner, Migration Files, Database Safety, and Build Queue pages require dry-run before future migration apply planning',
                'Real Migration Files planning foundation page and sidebar item',
                'Migration files permissions for migration_files.view and migration_files.manage',
                'Manual-only draft SQL migration files added under database/migrations for core users, business sources, products, status mapping, sync, orders, dispatch, returns, payables, invoices, printing, and supplier tools',
                'Draft SQL files include owner approval, backup-first, do-not-auto-run, and no page-load execution warnings',
                'Migration Files page documents file purpose, draft-only warning, manual apply, backup-before-apply, dry-run/check-first, apply order, rollback planning, and Red Issues Summary behavior',
                'Checkpoint database safety scan allows schema draft statements only in database/migrations SQL files and documentation while runtime code remains blocked',
                'Build Queue and Semi-Automation planning foundation page and sidebar item',
                'Build queue permissions for build_queue.view, build_queue.manage, build_automation.view, and build_automation.manage',
                'Safe one-build-at-a-time workflow documented: read queue, apply one task or small safe batch, run checkpoint, then stop for owner approval',
                'Semi-automation levels documented for manual workflow, queue-suggested next task, and small 2-3 page planning batches',
                'Blocked automation actions documented: auto commit, auto push, migration apply, OpenCart/WooCommerce sync, order import, payable mutation, stock deduction, and invoice generation',
                'Checkpoint-first rule, Git sync rule, owner approval before commit/push, and Red Issues Summary stop rule documented',
                'Planned build queue, build run, and red issue fields documented without automatic table creation or queue records',
                'Database Safety and Migration Runner pages state that build automation must never trigger migration apply',
                'Real Database Migration Runner planning foundation page and sidebar item',
                'Migration runner permissions for migrations.view, migrations.manage, migration_runner.view, and migration_runner.manage',
                'Owner/admin migration planning visibility without staff or supplier migration management access',
                'Manual-only, dry-run/check-first, backup-before-apply, owner/admin confirmation, audit/log, rollback, production safety, and Red Issues Summary rules documented',
                'Planned migration groups documented for users, activity logs, business sources, suppliers, products, stock/cost histories, status mappings, sync/imports, orders, dispatch, payables, returns, invoices, and supplier tool audit',
                'Planned migration, migration run log, and rollback fields documented without automatic table creation or migration records',
                'Database Safety links to Migration Runner planning and reinforces no page-load schema changes',
                'Local checkpoint route smoke includes Migration Runner and uses plain text ALL GREEN or RED ISSUES SUMMARY footer labels',
                'Manual and External Order planning foundation page and permissions without order creation or sync writes',
                'Sonamoni WooCommerce reference entry and offline/manual order planning before direct WooCommerce sync',
                'Manual order product mapping, shared vendor stock, cost snapshot, duplicate reference, confirmation, and audit rules documented',
                'Planned manual order, item, and audit fields documented without automatic table creation',
                'Supplier Tools planning foundation page and permissions without generator, calculator, or supplier tool writes',
                'Supplier Quick Invoice Generator planned as independent one-time supplier output with admin audit/history',
                'Simple Calculator planned as standalone tool with no payable, settlement, product cost, courier, stock, order, or accounting impact',
                'Planned supplier quick invoice, item, and audit fields documented without automatic table creation',
                'ERP Invoice and Packing Print planning foundation page and permissions without invoice generation or print writes',
                'Lokkisona-style, Sonamoni-style, and manual ERP invoice template planning from ERP order snapshots',
                'Real Lokkisona invoice sample, current invoice extension, and PIT Order Manager documented as read-only references only',
                'Customer invoice, packing slip, dispatch batch report, supplier product summary, return batch print, and payable settlement print types planned',
                'Sync Preview and Import Safety planning foundation page and permissions without live source connection or sync writes',
                'Multi-source plan for Lokkisona/OpenCart, Sonamoni/WooCommerce, and manual/external reference orders',
                'Shared supplier stock, ERP invoice planning, preview-before-import, duplicate blocking, and return candidate separation',
                'Planned sync preview, preview item, and import approval fields with preview totals and table columns documented',
                'Status Mapping and Sync Planning foundation page and permissions without OpenCart connection or mapping writes',
                'Source status to IBS workflow, Supplier Return, Lokkisona Return, and courier mapping rules documented',
                'Independent IBS workflow after sync, skip Missing/status 0, unmapped status safety, and Test Sync preview rules',
                'Sync preview counts, performance/sync safety limits, and planned mapping/sync preview/sync log fields documented',
                'Return Receive & Review Batch planning foundation page and permissions, owner/admin controlled',
                'Supplier Return vs Lokkisona Return separation with pre-submit total/cost-snapshot confirmation',
                'Supplier Return may affect payable only after review; Lokkisona Return has no payable deduction',
                'Return batch planning, payable adjustment review, remark/note, and optional image proof planned',
                'Planned return receive, return batch, return item, and payable adjustment fields documented',
                'Supplier Payable & Settlement planning foundation page and permissions without payable writes',
                'Product Cost Payable from dispatch cost snapshot, based on product cost only, not selling price',
                'Supplier Invoice, Additional Payable, Return/Damage Deduction, Payment, and Advance wording planned',
                'Net Payable to Supplier formula, owner/admin approval/audit, and supplier self-request rules planned',
                'Planned payable ledger, supplier invoice, supplier payment, and deduction fields documented',
                'Dispatch Batch / Dispatch Report planning foundation page and permissions without dispatch writes',
                'Locked dispatch gate after Shipped with single-supplier batches and batch locking documented',
                'Batch reference format DDMMYYYY(COUNT_ORDER) and cost snapshot for Product Cost Payable planned',
                'Delivery Stop exception, future print/export/download output, and dispatch performance rules planned',
                'Planned dispatch report and dispatch report item fields documented without database writes',
                'Order Workflow planning foundation page and permissions without order sync or database writes',
                'Independent IBS workflow with main fulfillment stages and exception stages documented',
                'Allowed transition matrix, no move back to New Order, and dispatch report gate after Shipped',
                'Source/status mapping used only at import, IBS workflow stays independent after sync',
                'Cost snapshot for payable, action confirmation/activity log, and performance/safety rules planned',
                'Channel-neutral order workflow ready for other suppliers, sources, and manual/offline orders',
                'Product Control foundation page and permissions without database writes or OpenCart sync',
                'Current supplier context Iqbal & Brothers with channel-neutral product/cost/stock planning',
                'Read-only platform fields and supplier-editable model, cost, and stock rules documented',
                'Cost/stock history, low-stock warning, option image, and dispatch/payable cost snapshot rules',
                'Planned product and variant fields for future sync and supplier operations',
                'Business Source and Sales Channel foundation page and permissions without database writes',
                'Current primary source Lokkisona.com documented without hard-coding future channels',
                'Manual, offline, ecommerce, marketplace, wholesale, and other source types prepared',
                'Future order source links prepared for supplier workflow, dispatch, returns, and payable',
                'Supplier foundation page and permissions without database writes',
                'Primary supplier Iqbal & Brothers documented with channel-neutral architecture',
                'Planned supplier fields and clean supplier accounting wording',
                'User Management foundation page and permission',
                'Future database user planning without writes',
                'Local checkpoint runner for PHP lint, route smoke, and safety checks',
                'Manual migration foundation',
                'Database safety page and permission',
                'Planned future table inventory',
                'Session authentication foundation',
                'Owner, admin, staff, and supplier roles prepared',
                'Config-backed permission policy service',
                'Permission-aware route protection and sidebar visibility',
                'File-backed activity log foundation',
                'Simple router',
                'Admin layout',
                'PDO database connection',
                'Health monitoring with database and storage status',
                'Git-based deployment',
            ],
        ];
    }
}
